
name: Start Crawling

on:
  schedule:
    - cron: '*/5 * * * *'


jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PWD: ${{ secrets.DB_PWD }}
        DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'

      - name: Start execution
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 stock.py
