
name: Start Crawling

on:
  schedule:
    - cron: '30 7,8 * * *'

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PWD: ${{ secrets.DB_PWD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'

      - name: Start execution
        run: |
          git pull
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 stock.py

      - name: GitHub Publish
        run: |
          git diff
          git add .
          git config --global user.email "dukenan006@163.com"
          git config --global user.name "shaun"
          git commit -m "update time,  $(date "+%a %b %d %H:%M %Z")" || echo "No changes to commit"
          git push